// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8umpDMHFCJ1T9cmoeximUsGp_CuUubU8',
    appId: '1:916501827123:web:deedcbd4e0275fa2681d46',
    messagingSenderId: '916501827123',
    projectId: 'you-pirate',
    authDomain: 'you-pirate.firebaseapp.com',
    storageBucket: 'you-pirate.firebasestorage.app',
    measurementId: 'G-L5KVJM7TKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2hCa0JtlGT6a219lN02fqLinXx3e3IE',
    appId: '1:916501827123:android:5d79d1be1a5be0d5681d46',
    messagingSenderId: '916501827123',
    projectId: 'you-pirate',
    storageBucket: 'you-pirate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRCb7lIiXuKPuFmi86pdv6n--G17RvS4s',
    appId: '1:916501827123:ios:49be57600e612707681d46',
    messagingSenderId: '916501827123',
    projectId: 'you-pirate',
    storageBucket: 'you-pirate.firebasestorage.app',
    iosBundleId: 'com.youpirate.youPirateApp',
  );
}
